instance creation
CONNECT_FAILED

	^self new
		reason: 2;
		description: 'Connect failed';
		yourself